# Generated by Django 4.1.5 on 2023-03-02 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=65)),
                ('autor', models.CharField(max_length=65)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=165)),
                ('tempoPreparo', models.IntegerField()),
                ('unidadeTempo', models.CharField(max_length=65)),
                ('qtdPorcoes', models.IntegerField()),
                ('passosPreparacao', models.TextField()),
                ('estaPublicado', models.BooleanField(default=False)),
                ('textoEmHTML', models.BooleanField(default=False)),
                ('dataModificacao', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('capas', models.ImageField(upload_to='recipes/capas/%Y/%m/%d')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.categoria')),
            ],
        ),
    ]
