# Generated by Django 4.1.5 on 2023-03-03 01:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_alter_receitas_autor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receitas',
            new_name='Receita',
        ),
    ]
