# Generated by Django 4.1.5 on 2023-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_receitas_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='capas',
            field=models.ImageField(blank=True, default='', upload_to='recipes/capas/%Y/%m/%d/'),
        ),
    ]
